#ElasticSearch, Logstash und Kibana Konfiguration großteils von https://github.com/jpetazzo/orchestration-workshop/blob/master/stacks/elk.yml übernommen
version: '3'
services:

  logstash:
    image: logstash
    command: |
      -e '
      input {
        gelf { }
        heartbeat { }
      }
      filter {
        ruby {
          code => "
            event.to_hash.keys.each { |k| event[ k.gsub('"'.'"','"'_'"') ] = event.remove(k) if k.include?'"'.'"' }
          "
        }
      }
      output {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
        stdout {
          codec => rubydebug
        }
      }'
    ports:
     - "12201:12201/udp"
    deploy:
      mode: replicated
      replicas: 3

  elasticsearch:
    image: elasticsearch:2

  kibana:
    image: kibana:4
    ports:
     - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200


networks:
  default: #Name des network ist default
    driver: overlay
    ipam:
      driver: default
    #  config:
    #   - subnet: 192.168.70.0/24
